### ISSUE TITLE
Enable Atom Feed

### ISSUE THREAD

**Issue by bjehlert** [walbourn/walbourn.github.io#4]
Could you enable Atom feeds for the blog? I followed your old blog using a feed making it much easier to be notified when new content was added.

https://help.github.com/en/articles/atom-rss-feeds-for-github-pages

**Comment by Klimax** [comment]
I'd like to second this.

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/walbourn/walbourn.github.io/commit/1f38003d5f1ad0b315a6685f5daee8501d9646c3)

**Comment by Klimax** [comment]
Hello, feed still doesn't show up on blog (not even in head). It can be accessed manually at https://walbourn.github.io/feed.xml so it is getting generated.
